services:
  users_service_db:
    container_name: users_service_db_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "users_trello"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 12345
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: "always"